version: '3.7'
services:
  cloudappidb:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    restart: always
    networks:
      - springcloud
    environment:
      POSTGRES_DB: cloudappidb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./database/:/var/lib/postgresql

  users-service:
    image: users-service:v1
    ports:
      - "8090:8080"
    restart: always
    networks:
      - springcloud
    depends_on:
      - cloudappidb
    environment:
      - TZ=America/Lima
      - PROFILE=prod
  
  sonarqube:
    image: sonarqube:8.5.1-community
    ports:
      - "9000:9000"
    networks:
      - springcloud
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonarqubedb:5435/sonarqubedb
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ulimits:
      nofile:
       soft: 65536
       hard: 65536
  
  sonarqubedb:
    image: postgres:12-alpine
    ports:
      - "5435:5432"
    networks:
      - springcloud
    environment:
      - POSTGRES_DB=sonarqubedb
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  springcloud:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:

